### ISSUE TITLE
[REQUEST](ASAP): Add recently added items action

### ISSUE THREAD

**Issue by rickzx98** [great-design-and-systems/item-service#1]
ACTION: getRecentlyAdded
METHOD: GET
PARAMS: categoryId (if no categoryId is specified fetch all items)
PAGINATE: YES, add mongoosePaginate plugin in item entity and use the paginate helper in gds-config

![image](https://cloud.githubusercontent.com/assets/6120021/22395800/75e80212-e583-11e6-9e20-ffcfb53a9530.png)

![image](https://cloud.githubusercontent.com/assets/6120021/22395808/99a02874-e583-11e6-9a2e-32ca4e1a3c34.png)

Result: Recently added items

**Comment by analynf** [comment]
You can use the following to get the recently added items:
GET /api/item/get-items?categoryId=value&page=1&limit=10&sort=-createdOn
