### ISSUE TITLE
[REQUEST](ASAP): Add get items by category id

### ISSUE THREAD

**Issue by rickzx98** [great-design-and-systems/item-service#2]
ACTION: getItemsByCategoryId
METHOD: GET
PARAMS: categoryId 
PAGINATE: YES, add mongoosePaginate plugin in item entity and use the paginate helper in gds-config

![image](https://cloud.githubusercontent.com/assets/6120021/22395800/75e80212-e583-11e6-9e20-ffcfb53a9530.png)

![image](https://cloud.githubusercontent.com/assets/6120021/22395808/99a02874-e583-11e6-9a2e-32ca4e1a3c34.png)

Result: Items by category

Additional logic: 
    Split item.description with space(\w) and add the array result to item with "fields" as its name.

e.g.
  ``` 
            items.forEach(item = >{
                  const fields = item.description.split(' ');
                  items.fields = fields;
           }
  ```

**Comment by analynf** [comment]
You can use the following to get items by category id:
GET /api/item/get-items?categoryId=value&page=1&limit=10&sort=-createdOn

**Comment by rickzx98** [comment]
I am fully aware of this function in getItem but I needed a different service name to separate concerns from UI perspective. Did you add the additional logic?
